# Generated by Django 5.2.16 on 2026-07-12 18:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('reporting_year', models.PositiveIntegerField(default=2025)),
                ('kind', models.CharField(choices=[('XML_UPLOAD', 'CRS XML upload'), ('MANUAL', 'Manual entry'), ('NIL', 'Nil return')], max_length=12)),
                ('message_type', models.CharField(choices=[('CRS701', 'CRS701 New data'), ('CRS702', 'CRS702 Corrections'), ('CRS703', 'CRS703 Nil return')], default='CRS701', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_CHECKER', 'Pending Checker'), ('SUBMITTED', 'Submitted'), ('UNDER_VALIDATION', 'Under Validation'), ('RETURNED', 'Returned for Correction'), ('ACCEPTED', 'Accepted'), ('IN_EXCHANGE', 'Included in Exchange')], default='DRAFT', max_length=18)),
                ('checker_comment', models.TextField(blank=True, default='')),
                ('uploaded_filename', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True, default='')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_filings', to='core.officerprofile')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_by', to='portal.filing')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_filings', to='core.officerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_ref_id', models.CharField(max_length=80, unique=True)),
                ('corr_doc_ref_id', models.CharField(blank=True, default='', max_length=80)),
                ('doc_type_indic', models.CharField(choices=[('OECD1', 'OECD1 New data'), ('OECD2', 'OECD2 Correction'), ('OECD3', 'OECD3 Deletion')], default='OECD1', max_length=6)),
                ('holder_name', models.CharField(max_length=200, verbose_name='Account holder name')),
                ('holder_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANISATION', 'Organisation')], default='INDIVIDUAL', max_length=12)),
                ('residence_country', models.CharField(max_length=2, verbose_name='Residence jurisdiction')),
                ('foreign_tin', models.CharField(blank=True, default='', max_length=40, verbose_name='TIN issued by residence jurisdiction')),
                ('account_number', models.CharField(max_length=40)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('dividends', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('interest', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('gross_proceeds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_reports', to='portal.filing')),
            ],
            options={
                'ordering': ['doc_ref_id'],
            },
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(choices=[('MAKER', 'Maker'), ('CHECKER', 'Checker')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Checker approval'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10)),
                ('is_primary_user', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=True)),
                ('failed_logins', models.PositiveIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rfi', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='filing',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filings_checked', to='portal.portaluser'),
        ),
        migrations.AddField(
            model_name='filing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filings_created', to='portal.portaluser'),
        ),
        migrations.CreateModel(
            name='ReportingFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('tin', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('COMMERCIAL_BANK', 'Commercial Bank'), ('MERCHANT_BANK', 'Merchant Bank'), ('INSURANCE', 'Insurance and Life Assurance'), ('INVESTMENT_ADVISER', 'Investment Adviser'), ('TRUSTEE', 'Trustee'), ('ASSET_MANAGER', 'Asset Manager'), ('ISSUING_HOUSE', 'Issuing House'), ('BROKER_DEALER', 'Broker/Dealer'), ('OTHER', 'Other')], max_length=30)),
                ('regulator', models.CharField(choices=[('CBN', 'Central Bank of Nigeria'), ('SEC', 'Securities and Exchange Commission'), ('NAICOM', 'National Insurance Commission')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='SUBMITTED', max_length=15)),
                ('pu_name', models.CharField(max_length=120, verbose_name='Primary User name')),
                ('pu_designation', models.CharField(max_length=120, verbose_name='Primary User designation')),
                ('pu_email', models.EmailField(max_length=254, verbose_name='Primary User email')),
                ('pu_phone', models.CharField(max_length=30, verbose_name='Primary User phone')),
                ('ceo_letter', models.FileField(blank=True, null=True, upload_to='ceo_letters/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('check_tin', models.BooleanField(default=False, verbose_name='TIN verified against the taxpayer register')),
                ('check_ceo_letter', models.BooleanField(default=False, verbose_name='CEO letter introducing the PU sighted')),
                ('check_licence', models.BooleanField(default=False, verbose_name='Sector regulator licence confirmed')),
                ('check_classification', models.BooleanField(default=False, verbose_name='CRS classification confirmed')),
                ('review_notes', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(blank=True, choices=[('APPROVE', 'Recommend approval'), ('REJECT', 'Recommend rejection')], default='', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_enrolments', to='core.officerprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrolments', to='core.officerprofile')),
            ],
            options={
                'verbose_name': 'Reporting Financial Institution',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='portaluser',
            name='rfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='portal.reportingfi'),
        ),
        migrations.AddField(
            model_name='filing',
            name='rfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='portal.reportingfi'),
        ),
        migrations.CreateModel(
            name='ValidationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=8)),
                ('code', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('overridden', models.BooleanField(default=False)),
                ('override_justification', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='portal.accountreport')),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='portal.filing')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.officerprofile')),
            ],
            options={
                'ordering': ['account_report__doc_ref_id', 'code'],
            },
        ),
    ]
