# Generated by Django 5.2.16 on 2026-07-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
    ]
