# Generated by Django 5.2.16 on 2026-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_accountreport_superseded'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingfi',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Registered office address'),
        ),
    ]
