# Generated by Django 5.2.16 on 2026-07-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_reportingfi_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingfi',
            name='category',
            field=models.CharField(choices=[('INVESTMENT_ENTITY', 'Investment Entities'), ('DEPOSITORY_INSTITUTION', 'Depository Institutions'), ('CUSTODIAL_INSTITUTION', 'Custodial Institutions'), ('SPECIFIED_INSURANCE', 'Specified Insurance Companies')], max_length=30),
        ),
    ]
