# Generated by Django 5.2.16 on 2026-07-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_reportingfi_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingfi',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Financial Institution email'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Financial Institution phone'),
        ),
    ]
