# Generated by Django 5.2.16 on 2026-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_reportingfi_email_reportingfi_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingfi',
            name='address',
        ),
        migrations.RemoveField(
            model_name='reportingfi',
            name='pu_name',
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City or town'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='id_documents/', verbose_name='Primary User identification'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='phone_cc',
            field=models.CharField(blank=True, default='+234', max_length=6, verbose_name='Phone country code'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Post code'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='pu_first_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Primary User first name'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='pu_phone_cc',
            field=models.CharField(blank=True, default='+234', max_length=6, verbose_name='Primary User phone country code'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='pu_surname',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Primary User surname'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='state_province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='State or province'),
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='reportingfi',
            name='pu_designation',
            field=models.CharField(max_length=120, verbose_name='Primary User position'),
        ),
    ]
