# Generated by Django 5.2.16 on 2026-07-17 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_reportingfi_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], max_length=15)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='portal.reportingfi')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
