# Generated by Django 5.2.16 on 2026-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_enrolmentstatusevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingfi',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('APPROVE', 'Approval'), ('REJECT', 'Rejection')], default='', max_length=10),
        ),
    ]
