# Generated by Django 5.2.16 on 2026-07-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_reportingfi_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingfi',
            name='regulator',
        ),
        migrations.AddField(
            model_name='reportingfi',
            name='enrolment_type',
            field=models.CharField(choices=[('FINANCIAL_ENTITY', 'Financial Entities'), ('STAKEHOLDER', 'Financial Entity Stakeholders'), ('INDIVIDUAL', 'Individuals')], default='FINANCIAL_ENTITY', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportingfi',
            name='check_licence',
            field=models.BooleanField(default=False, verbose_name='Regulatory licence confirmed'),
        ),
    ]
