# Generated by Django 5.2.16 on 2026-07-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_reportingfi_regulator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Filing name'),
        ),
        migrations.AddField(
            model_name='filing',
            name='period_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Period end date'),
        ),
        migrations.AlterField(
            model_name='filing',
            name='kind',
            field=models.CharField(choices=[('XML_UPLOAD', 'CRS XML upload Filing'), ('MANUAL', 'CRS Manual Entry Filing'), ('NIL', 'Nil return'), ('PU_CHANGE', 'Primary User Change Notice'), ('ENTITY_DEACTIVATION', 'Reporting Entity Deactivation'), ('ENTITY_INFO_CHANGE', 'Change of reporting entity information')], max_length=20),
        ),
    ]
