# Generated by Django 5.2.16 on 2026-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_filing_name_filing_period_end_date_alter_filing_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='message_reference',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Message reference'),
        ),
        migrations.AddField(
            model_name='filing',
            name='receiving_country',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Receiving country'),
        ),
        migrations.AddField(
            model_name='filing',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='filing',
            name='sending_company_in',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Sending Company IN'),
        ),
    ]
