# Generated by Django 5.2.16 on 2026-07-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_filing_message_reference_filing_receiving_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingfi',
            name='pu_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
