# Generated by Django 5.2.16 on 2026-07-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_reportingfi_pu_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='acct_holder_type',
            field=models.CharField(blank=True, choices=[('CRS101', 'CRS101 Passive NFE with controlling person(s)'), ('CRS102', 'CRS102 CRS Reportable Person'), ('CRS103', 'CRS103 Passive NFE that is a CRS Reportable Person')], default='', max_length=6, verbose_name='Entity account holder type'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='address_country',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Address country'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='birth_city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='City of birth'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Account holder address'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='self_certification',
            field=models.CharField(blank=True, choices=[('OBTAINED', 'Obtained and validated'), ('CURED', 'Cured after remediation'), ('NOT_OBTAINED', 'Not obtained (undocumented)')], default='', max_length=14),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='tin_unavailable_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Reason TIN not reported'),
        ),
        migrations.CreateModel(
            name='ControllingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Controlling person name')),
                ('residence_country', models.CharField(max_length=2, verbose_name='Residence jurisdiction')),
                ('tin', models.CharField(blank=True, default='', max_length=40, verbose_name='TIN')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Address')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('ctrlg_person_type', models.CharField(choices=[('CRS801', 'CRS801 Ownership of legal person'), ('CRS802', 'CRS802 Other means of control of legal person'), ('CRS803', 'CRS803 Senior managing official'), ('CRS804', 'CRS804 Trust settlor'), ('CRS805', 'CRS805 Trust trustee'), ('CRS806', 'CRS806 Trust protector'), ('CRS807', 'CRS807 Trust beneficiary'), ('CRS808', 'CRS808 Trust other'), ('CRS809', 'CRS809 Legal arrangement settlor-equivalent'), ('CRS810', 'CRS810 Legal arrangement trustee-equivalent'), ('CRS811', 'CRS811 Legal arrangement protector-equivalent'), ('CRS812', 'CRS812 Legal arrangement beneficiary-equivalent'), ('CRS813', 'CRS813 Legal arrangement other-equivalent')], default='CRS801', max_length=6, verbose_name='Controlling person type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlling_persons', to='portal.accountreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
