# Generated by Django 5.2.16 on 2026-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_accountreport_acct_holder_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='kind',
            field=models.CharField(choices=[('XML_UPLOAD', 'CRS XML upload Filing'), ('EXCEL_UPLOAD', 'CRS Excel Upload Filing'), ('MANUAL', 'CRS Manual Entry Filing'), ('NIL', 'Nil return'), ('PU_CHANGE', 'Primary User Change Notice'), ('ENTITY_DEACTIVATION', 'Reporting Entity Deactivation'), ('ENTITY_INFO_CHANGE', 'Change of reporting entity information')], max_length=20),
        ),
    ]
