# Generated by Django 5.2.16 on 2026-07-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_filing_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolmentstatusevent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Declined'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], max_length=15),
        ),
        migrations.AlterField(
            model_name='reportingfi',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Declined'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='SUBMITTED', max_length=15),
        ),
    ]
