# Generated by Django 5.2.16 on 2026-07-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_enrolmentstatusevent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingfi',
            name='pu_middle_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Primary User middle name'),
        ),
        migrations.AlterField(
            model_name='reportingfi',
            name='pu_first_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Primary User other names'),
        ),
    ]
