# Generated by Django 5.2.16 on 2026-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_reportingfi_pu_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreport',
            name='holder_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANISATION', 'Entity')], default='INDIVIDUAL', max_length=12),
        ),
        migrations.AlterField(
            model_name='filing',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_CHECKER', 'Pending Submission'), ('SUBMITTED', 'Submitted'), ('UNDER_VALIDATION', 'Under Validation'), ('RETURNED', 'Returned for Correction'), ('ACCEPTED', 'Accepted'), ('IN_EXCHANGE', 'Included in Exchange')], default='DRAFT', max_length=18),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='role',
            field=models.CharField(choices=[('MAKER', 'Secondary User'), ('CHECKER', 'Primary User')], max_length=10),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10),
        ),
    ]
