# Generated by Django 5.2.16 on 2026-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_accountreport_holder_type_alter_filing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='acct_number_type',
            field=models.CharField(blank=True, choices=[('OECD601', 'OECD601 IBAN'), ('OECD602', 'OECD602 Other Bank Account Number'), ('OECD603', 'OECD603 ISIN'), ('OECD604', 'OECD604 Other Securities Information Number'), ('OECD605', 'OECD605 Other (e.g. insurance contract)')], default='', max_length=7, verbose_name='Account number type'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='birth_city_subentity',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Birth city subentity'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='birth_country_code',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Country of birth'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='birth_former_country_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Former country of birth'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='closed_account',
            field=models.BooleanField(default=False, verbose_name='Account closed in the reporting period'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='dormant_account',
            field=models.BooleanField(default=False, verbose_name='Account dormant'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_building_identifier',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_city',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_country_subentity',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='State / region'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_first_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_last_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_post_code',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Post code'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='controllingperson',
            name='address_country',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Address country'),
        ),
        migrations.AddField(
            model_name='controllingperson',
            name='birth_city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='City of birth'),
        ),
        migrations.AddField(
            model_name='controllingperson',
            name='birth_country_code',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Country of birth'),
        ),
        migrations.AddField(
            model_name='controllingperson',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='controllingperson',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='controllingperson',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Last name'),
        ),
    ]
