# Generated by Django 5.2.16 on 2026-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_accountreport_acct_number_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingfi',
            name='pu_place_of_birth',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Place of birth'),
        ),
    ]
