# Generated by Django 5.2.16 on 2026-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_reportingfi_pu_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='holder_middle_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='controllingperson',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Middle name'),
        ),
    ]
