# Generated by Django 5.2.16 on 2026-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_accountreport_holder_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='holder_district_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_floor_identifier',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_pob',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='P.O. box'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='holder_suite_identifier',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Suite'),
        ),
    ]
