# Generated by Django 5.2.16 on 2026-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_accountreport_holder_district_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='notice_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
