# Generated by Django 5.2.16 on 2026-08-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_filing_notice_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='source_line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
