# Generated by Django 5.2.16 on 2026-07-12 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoOutboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('to_address', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('REGISTRATION_OFFICER', 'Registration Officer'), ('REGISTRATION_SUPERVISOR', 'Registration Supervisor'), ('RETURNS_OFFICER', 'Returns Officer'), ('RETURNS_SUPERVISOR', 'Returns Supervisor'), ('EXCHANGE_OFFICER', 'Exchange Officer'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor')], max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('REGISTRATION_OFFICER', 'Registration Officer'), ('REGISTRATION_SUPERVISOR', 'Registration Supervisor'), ('RETURNS_OFFICER', 'Returns Officer'), ('RETURNS_SUPERVISOR', 'Returns Supervisor'), ('EXCHANGE_OFFICER', 'Exchange Officer'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor')], max_length=40)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('passcode_hash', models.CharField(max_length=200)),
                ('session_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_if_unused_at', models.DateTimeField()),
                ('first_used_at', models.DateTimeField(blank=True, null=True)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('CONSUMED', 'Consumed')], default='ISSUED', max_length=12)),
                ('bound_session_key', models.CharField(blank=True, default='', max_length=64)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_credential', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='core.officerprofile')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(max_length=120)),
                ('actor_role', models.CharField(blank=True, default='', max_length=40)),
                ('surface', models.CharField(default='backoffice', max_length=12)),
                ('action', models.CharField(max_length=60)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('before_state', models.CharField(blank=True, default='', max_length=120)),
                ('after_state', models.CharField(blank=True, default='', max_length=120)),
                ('detail', models.TextField(blank=True, default='')),
                ('flagged', models.BooleanField(default=False)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.issuedcredential')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
