# Generated by Django 5.2.16 on 2026-07-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedcredential',
            name='role',
        ),
        migrations.RemoveField(
            model_name='officerprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='issuedcredential',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Roles'),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Assigned roles'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
