# Generated by Django 5.2.16 on 2026-07-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_issuedcredential_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Phone number'),
        ),
    ]
