# Generated by Django 5.2.16 on 2026-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_officerprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedcredential',
            name='session_hours',
        ),
        migrations.AddField(
            model_name='issuedcredential',
            name='session_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
