# Generated by Django 5.2.16 on 2026-07-12 18:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.PositiveIntegerField()),
                ('message_ref_id', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('FILE_ERROR', 'Rejected, file error'), ('RECORD_ERRORS', 'Record errors outstanding'), ('ACCEPTED', 'Accepted'), ('APPROVED', 'Approved for domestic use'), ('DISSEMINATED', 'Disseminated')], default='RECEIVED', max_length=14)),
                ('simulate_file_error', models.CharField(blank=True, default='', max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('file_checked_at', models.DateTimeField(blank=True, null=True)),
                ('records_checked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disseminated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('activated_since', models.DateField()),
                ('key_fingerprint', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_ref_id', models.CharField(max_length=80)),
                ('holder_name', models.CharField(max_length=200)),
                ('ng_tin', models.CharField(blank=True, default='', max_length=40, verbose_name='Nigerian TIN')),
                ('account_number', models.CharField(max_length=40)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('has_error', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, default='', max_length=10)),
                ('error_detail', models.CharField(blank=True, default='', max_length=200)),
                ('corrected', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='exchange.inboundfile')),
            ],
            options={
                'ordering': ['doc_ref_id'],
            },
        ),
        migrations.AddField(
            model_name='inboundfile',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_files', to='exchange.partnerjurisdiction'),
        ),
        migrations.CreateModel(
            name='ExchangePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.PositiveIntegerField()),
                ('message_ref_id', models.CharField(max_length=40, unique=True)),
                ('message_type', models.CharField(choices=[('CRS701', 'CRS701 New data'), ('CRS702', 'CRS702 Corrections')], default='CRS701', max_length=8)),
                ('status', models.CharField(choices=[('BUILT', 'Built'), ('TRANSMITTING', 'Transmitting'), ('TRANSMITTED', 'Transmitted'), ('ACCEPTED', 'Accepted'), ('FILE_ERROR', 'Rejected, file error'), ('RECORD_ERRORS', 'Record errors reported'), ('ARCHIVED', 'Archived')], default='BUILT', max_length=16)),
                ('pipeline_step', models.PositiveSmallIntegerField(default=1)),
                ('xml_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('corrects_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_packages', to='exchange.exchangepackage')),
                ('records', models.ManyToManyField(related_name='packages', to='portal.accountreport')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='exchange.partnerjurisdiction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_year', models.PositiveIntegerField()),
                ('months_in_default', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.officerprofile')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_notices', to='portal.reportingfi')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Received from partner'), ('OUTBOUND', 'Issued to partner')], max_length=10)),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('FILE_ERROR', 'File error'), ('RECORD_ERROR', 'Record errors')], max_length=14)),
                ('error_code', models.CharField(blank=True, default='', max_length=10)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbound_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_messages', to='exchange.inboundfile')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_messages', to='exchange.exchangepackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_ref_id', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=10)),
                ('detail', models.CharField(max_length=200)),
                ('resolved', models.BooleanField(default=False)),
                ('correction_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolves_errors', to='portal.accountreport')),
                ('status_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_errors', to='exchange.statusmessage')),
            ],
            options={
                'ordering': ['doc_ref_id'],
            },
        ),
    ]
