# Generated by Django 5.2.16 on 2026-07-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=40, unique=True, verbose_name='Nigerian TIN')),
                ('name', models.CharField(max_length=200)),
                ('tax_office', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inboundfile',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundrecord',
            name='match_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inboundrecord',
            name='match_basis',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inboundrecord',
            name='match_status',
            field=models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched')], default='UNMATCHED', max_length=10),
        ),
        migrations.AddField(
            model_name='inboundrecord',
            name='risk_rating',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General monitoring'), ('SPECIFIC', 'Specific review'), ('ENHANCED', 'Enhanced review')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='inboundfile',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('FILE_ERROR', 'Rejected, file error'), ('RECORD_ERRORS', 'Record errors outstanding'), ('ACCEPTED', 'Accepted'), ('APPROVED', 'Approved for domestic use'), ('MATCHED', 'Matched to taxpayers'), ('DISSEMINATED', 'Disseminated')], default='RECEIVED', max_length=14),
        ),
        migrations.AddField(
            model_name='inboundrecord',
            name='matched_taxpayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_records', to='exchange.taxpayer'),
        ),
    ]
