# Generated by Django 5.2.16 on 2026-07-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_taxpayer_inboundfile_matched_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PenaltyNotice',
        ),
    ]
