# Generated by Django 5.2.16 on 2026-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_delete_penaltynotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangepackage',
            name='message_type',
            field=models.CharField(choices=[('CRS701', 'CRS701 New data'), ('CRS702', 'CRS702 Corrections'), ('CRS703', 'CRS703 Nil return')], default='CRS701', max_length=8),
        ),
    ]
