# Generated by Django 5.2.16 on 2026-08-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_credential_session_months'),
        ('exchange', '0004_alter_exchangepackage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepackage',
            name='file_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exchangepackage',
            name='regime',
            field=models.CharField(choices=[('CRS', 'CRS'), ('CARF', 'CARF')], default='CRS', max_length=4),
        ),
        migrations.AddField(
            model_name='exchangepackage',
            name='responsible_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_packages', to='core.officerprofile'),
        ),
        migrations.AddField(
            model_name='inboundfile',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_files_reviewed', to='core.officerprofile'),
        ),
        migrations.AddField(
            model_name='inboundfile',
            name='regime',
            field=models.CharField(choices=[('CRS', 'CRS'), ('CARF', 'CARF')], default='CRS', max_length=4),
        ),
        migrations.AlterField(
            model_name='statusmessage',
            name='outcome',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WARNING', 'Accepted with warnings'), ('FILE_ERROR', 'File error'), ('RECORD_ERROR', 'Record errors')], max_length=14),
        ),
    ]
