# Generated by Django 5.2.16 on 2026-08-03 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_exchangepackage_file_version_exchangepackage_regime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('NRS', 'NRS own signing certificate'), ('PARTNER', 'Partner jurisdiction')], default='PARTNER', max_length=8)),
                ('subject', models.CharField(max_length=120)),
                ('fingerprint', models.CharField(max_length=64)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('revoked', models.BooleanField(default=False)),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='exchange.partnerjurisdiction')),
            ],
            options={
                'ordering': ['valid_to'],
            },
        ),
    ]
