"""Supervision Centre URL routes."""
from django.urls import path

from backoffice import (
    views,
    views_admin,
    views_registration,
    views_reports,
    views_returns,
    views_supervision,
)
from exchange import views as exchange_views

urlpatterns = [
    path("reports/", views_reports.reports),
    path("institutions/", views_supervision.institutions),
    path("compliance/", views_supervision.compliance),
    path("exchange/", exchange_views.workspace),
    path("exchange/monitoring/", exchange_views.cts_monitoring),
    path("exchange/build/", exchange_views.build),
    path("exchange/build-nil/", exchange_views.build_nil),
    path("exchange/packages/<int:package_id>/", exchange_views.package_detail),
    path("exchange/packages/<int:package_id>/advance/", exchange_views.package_advance),
    path("exchange/packages/<int:package_id>/partner-response/", exchange_views.package_partner_response),
    path("exchange/packages/<int:package_id>/resubmit/", exchange_views.package_resubmit),
    path("exchange/packages/<int:package_id>/correct/", exchange_views.correct_package),
    path("exchange/corrections/", exchange_views.corrections),
    path("exchange/inbound/", exchange_views.inbound_list),
    path("exchange/inbound/<int:file_id>/", exchange_views.inbound_detail),
    path("exchange/inbound/<int:file_id>/file-check/", exchange_views.inbound_file_check),
    path("exchange/inbound/<int:file_id>/record-check/", exchange_views.inbound_record_check),
    path("exchange/inbound/<int:file_id>/partner-correction/", exchange_views.inbound_partner_correction),
    path("exchange/inbound/<int:file_id>/approve/", exchange_views.inbound_approve),
    path("exchange/inbound/<int:file_id>/match/", exchange_views.inbound_match),
    path("exchange/inbound/<int:file_id>/resolve-identities/", exchange_views.inbound_resolve_identities),
    path("exchange/inbound/<int:file_id>/disseminate/", exchange_views.inbound_disseminate),
    path("exchange/tax-authority-view/", exchange_views.tax_authority_view),
    path("returns/", views_returns.queue),
    path("returns/<int:filing_id>/", views_returns.detail),
    path("returns/<int:filing_id>/download/", views_returns.download),
    path("returns/<int:filing_id>/validate/", views_returns.validate),
    path("returns/<int:filing_id>/return/", views_returns.return_to_rfi),
    path("returns/<int:filing_id>/approve/", views_returns.approve),
    path("returns/<int:filing_id>/findings/<int:finding_id>/override/", views_returns.override_warning),
    path("registration/", views_registration.queue),
    path("registration/<int:rfi_id>/", views_registration.detail),
    # Retired with the recorded-assessment step (not in the Vizor structure):
    # path("registration/<int:rfi_id>/review/", views_registration.review),
    path("registration/<int:rfi_id>/decide/", views_registration.decide),
    path("registration/<int:rfi_id>/standing/", views_registration.standing),
    path("login/", views.login_view),
    path("logout/", views.logout_view),
    path("", views.dashboard),
    path("admin-console/", views_admin.console),
    path("admin-console/officers/", views_admin.officers),
    path("admin-console/officers/<int:officer_id>/", views_admin.officer_history),
    path("admin-console/officers/<int:officer_id>/roles/", views_admin.officer_roles),
    path("admin-console/sessions/", views_admin.live_sessions),
    path("admin-console/credentials/<int:credential_id>/revoke/", views_admin.revoke_credential),
    path("audit/", views.audit_log),
    path("audit/credentials/", views.credential_history),
]
